### PR TITLE
Added OpsMx (Spinnaker & Continuous Verification) Readme. 

### PR DESCRIPTION
**Pull request by dommety**
Hi, We at OpsMx are working on Tekton to provide Continous Verification with Tekton Rollouts and also looking into integrating Spinnaker and Tekton.

### CODE REVIEW

**Comment by vdemeester** [comment]
@dommety can you sign the CLA ? :angel: :pray:

**Comment by dommety** [comment]
@googlebot I signed it!

**Comment by vdemeester** [comment]
@dommety last thingk I promise: can you squash the commits ? (the `Create .DS_Store` commit is weirding me out :stuck_out_tongue:)

**Comment by dibyom** [comment]
@dommety I think this just needs a squash and then its ready to go!

**Comment by vdemeester** [comment]
ping @dommety (for squashing :pray:)

**Comment by bobcatfish** [comment]
quick ping - we'd love to merge this @dommety but it looks like the commits need a squash first 🙏

**Pull request closed without merging**
