### PR TITLE
Add Ozone

### PR DESCRIPTION
**Pull request by moteesh-reddy**
Signed-off-by: moteesh-in2tive <moteesh@in2tive.ai>

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @bobcatfish @afrittoli

**Review by afrittoli — COMMENTED** [review]
Nice!

NIT: I wonder if you'd like to include a link? e.g. https://in2tive.ai/

/approve

**Comment by moteesh-reddy** [comment]
@afrittoli , included the link to the product website

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
