### PR TITLE
Added Alibaba to Tekton friends

### PR DESCRIPTION
**Pull request by resouer**
Glad to be involved.

### CODE REVIEW

**Review by dlorenc — APPROVED** [review]

**Comment by bobcatfish** [comment]
Hey there @resouer !

> We implemented Canary Analysis + Progressive Deployment based on Tekton

Quick question, do you have any Tasks you use for your your canary analysis and deployment that you'd be interested in sharing? e.g. via https://github.com/tektoncd/catalog or even just in a gist - @kimsterv are working on a presentation for Google Next Tokyo next week about canary deployment and it would be super cool if we could demo a Task you've created :D 

No worries if not tho, it's one thing to make a Task that works for you and another to make it more broadly usable :)

**Comment by resouer** [comment]
@bobcatfish We would love to share of course, while `next week` would be too rush for us as this work involves a Canary deploy controller which performs the analysis & progressive traffic adjustment. Maybe we can provide you with a page of doc or sth? We also submitted a KubeCon NA talk, while you know, that part would require some more luck. 🤔

**Comment by bobcatfish** [comment]
Haha I thought next week was probably a bit too rushed 😅  No worries at all! Would love to see it though when/if you get a chance :)

> Maybe we can provide you with a page of doc or sth? 

That would be great too!

> We also submitted a KubeCon NA talk, while you know, that part would require some more luck. 🤔

I look forward to seeing it! :D 🤞 for it to be accepted! And also by the way, we will probably be sending out a CFP soon for the co-located CDF event as well ;)

**Pull request merged**
