### PR TITLE
Update OWNERS to include skaegi/me

### PR DESCRIPTION
**Pull request by skaegi**

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
/lgtm
/hold

**Review by vdemeester — APPROVED** [review]

**Comment by skaegi** [comment]
@dlorenc @vdemeester Could some kind soul please remove the `do-not-merge/hold` label. I think this happens because of an edit to the OWNERS file.

**Comment by vdemeester** [comment]
@skaegi I am the one who put the hold, to let time for other OWNER put their lgtm 😇

To remove it “/hold cancel” 😇(but only owner can do that, will do, letting a few hours still)

**Pull request merged**
